pipeline {
    agent { label 'AGENT-1' }
    environment { 
        PROJECCT = 'EXPENSE'
        COMPONENT = 'BACKEND'
        ENVIRONMENT = 'DEV'
    }
    options { 
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm') 
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'Pick something')
    }
    stages {
        stage('Install Terraform') {
            steps {
                sh """
                wget https://releases.hashicorp.com/terraform/1.11.1/terraform_1.11.1_linux_amd64.zip
                unzip -o terraform_1.11.1_linux_amd64.zip
                sudo mv terraform /usr/local/bin/

                terraform version
                """
            }
        }
        stage('Init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 30-rds
                            terraform init -reconfigure
                            terraform plan
                        """
                    }
                }
            }
        }
        stage('Apply') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws-creds') {
                        sh """
                            cd 30-rds
                            terraform apply -auto-approve
                        """
                    }
                }
            }
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}